blizzard/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from website.views import *
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar
from django.urls import re_path
from django.conf import settings
from django.views import generic


sitemaps = {
    'static' : StaticViewSitemap,
    'blog' : BlogSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),

    path('accounts/', include('allauth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Maintenance Mode
if settings.MAINTENANCE_MODE:
   urlpatterns.insert(0, re_path(r'^', generic.TemplateView.as_view(template_name='maintenance.html'), name='maintenance'))

blog/urls.py
from django.urls import path, include
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='home'),
    path('<int:pid>' ,blog_single,name='single'),
    path('category/<str:cat_name>' ,blog_view,name='category'),
    path('tag/<str:tag_name>' ,blog_view,name='tag'),
    path('author/<str:author_username>', blog_view,name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed', LatestEntriesFeed()),

]

website/urls.py
from django.urls import path, include
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('contact', contact_view, name='contact'),
    path('about', about_view, name='about'),
    path('newsletter', newsletter_view, name='newsletter'),
]

website/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return self.name

class NewsLetter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

website/forms.py
from django import forms
from website.models import Contact, NewsLetter
from captcha.fields import CaptchaField

class NameForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    subject = forms.CharField(max_length=255, required=True)
    message = forms.CharField(widget=forms.Textarea())

class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    
    class Meta:
        model = Contact
        fields = ['name','email', 'subject', 'message']

class NewsLetterForm(forms.ModelForm):

    class Meta:
        model = NewsLetter
        fields = '__all__'

website/views.py
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from blog.models import Post
from website.models import Contact
from website.forms import NameForm,ContactForm,NewsLetterForm
from django.contrib import messages


def index_view(request):
    posts = Post.objects.filter(status=1)
    context = {'posts': posts}
    return render(request,'website/index.html',context)

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            messages.add_message(request, messages.SUCCESS, 'Ticket submitted successfully')
            form.save()
        else:
            messages.add_message(request, messages.ERROR, "Your ticket didn't submit.")
    form = ContactForm()
    return render(request, 'website/contact.html', {'form': form})

def about_view(request):
    return render(request, 'website/about.html')

def home_view(request):
    return render(request, 'website/index-2.html')

def blog_view(request):
    return render(request, 'blog/blog.html')

def newsletter_view(request):
    if request.method == 'POST':
        form = NewsLetterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your Email submitted successfully')
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

    

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<body>

    <!-- main-area -->
    <main>

        <!-- breadcrumb-area -->
        <section class="breadcrumb-area breadcrumb-bg">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="breadcrumb-content text-center">
                            <h2>contact <span>info</span></h2>
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
                                    <li class="breadcrumb-item"><a href="#">pages</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">contact</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- breadcrumb-area-end -->

        <!-- contact-area -->
        <section class="contact-area pt-120 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div id="contact-map"></div>
                    </div>
                    <div class="col-lg-6 pl-45">
                        <div class="section-title title-style-three mb-20">
                            <h2>CONTACT US ABOUT <span>PRESS</span></h2>
                        </div>
                        <div class="contact-info-list mb-40">
                            <ul>
                                <li><i class="fas fa-map-marker-alt"></i>Walking Park, Los Angeles, Brockland, USA</li>
                                
                        </div>
                        <div class="contact-form">
                            <form action="{% url 'website:contact' %}" method="post">
                                {% csrf_token %}
                                <textarea name="message" placeholder="Write Message..."></textarea>
                                <div class="row">
                                    <div class="col-md-6">
                                        <input name='name' type="text" placeholder="Your Name">
                                    </div>
                                    <div class="col-md-6">
                                        <input name='email' type="email" placeholder="Your Mail">
                                    </div>
                                    <div class="col-md-6">
                                        <input name='subject' type="text" placeholder="subject">
                                    </div>
                                    <div class="col-md-6">
                                        {{form.captcha}}
                                    </div>
                                </div>
                                <button type='submit'>SUBMIT MESSAGE</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- contact-area-end -->



    </main>
    <!-- main-area-end -->


    {% endblock %}