blizzard/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from website.views import *
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar
from django.urls import re_path
from django.conf import settings
from django.views import generic


sitemaps = {
    'static' : StaticViewSitemap,
    'blog' : BlogSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),

    path('accounts/', include('allauth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Maintenance Mode
if settings.MAINTENANCE_MODE:
   urlpatterns.insert(0, re_path(r'^', generic.TemplateView.as_view(template_name='maintenance.html'), name='maintenance'))

blog/urls.py
from django.urls import path, include
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='home'),
    path('<int:pid>' ,blog_single,name='single'),
    path('category/<str:cat_name>' ,blog_view,name='category'),
    path('tag/<str:tag_name>' ,blog_view,name='tag'),
    path('author/<str:author_username>', blog_view,name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed', LatestEntriesFeed()),

]

website/urls.py
from django.urls import path, include
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('contact', contact_view, name='contact'),
    path('about', about_view, name='about'),
    path('newsletter', newsletter_view, name='newsletter'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    image = models.ImageField(upload_to='blog/',default='blog/default.jpg')
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_required = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid':self.id})

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.CharField(max_length=255)
    approve = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['post','name','email', 'message']

blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from blog.models import Post,Comment
from blog.models import Category
from blog.forms import CommentForm
from django.contrib import messages

# Create your views here.
def blog_view(request,**kwargs):
    posts = Post.objects.filter(status=1)
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
    posts = Paginator(posts,4)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {'posts':posts}
    return render(request,'blog/blog-home.html', context)

def blog_single(request,pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Submitted successfully')
        else:
            messages.add_message(request, messages.ERROR, 'Could not submit your comment')
    posts = Post.objects.filter(status=1)
    post = get_object_or_404(posts,pk=pid,status=1)
    post.counted_views +=1
    post.save()
    comments = Comment.objects.filter(post=post.id,approve=True)
    next_post = Post.objects.filter(id__gt=post.id).order_by('id').first()
    previous_post = Post.objects.filter(id__lt=post.id).order_by('id').last()
    form = CommentForm()
    context = {'post':post ,'previous_post':previous_post,'next_post':next_post,'comments':comments,'form':form}
    if not post.login_required:
        return render(request,'blog/blog-single.html', context)
    else:
        if request.user.is_authenticated:
            return render(request,'blog/blog-single.html',context)
        else:
            return redirect('/accounts/login')


def blog_category(request, cat_name):
    posts = Post.objects.filter(status=1)
    posts = posts.filter(category__name=cat_name)
    context = {'posts':posts}
    return render(request,'blog/blog-home.html',context)

def blog_search(request):
    posts = Post.objects.filter(status=1)
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts = posts.filter(content__contains=s)
    posts = Paginator(posts,4)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {'posts':posts}
    return render(request,'blog/blog-home.html', context)

templates/blog/blog-author.html
{% load static %}
<div class="widget mb-45">
    <div class="sidebar-about">
        <div class="sidebar-about-thumb">
            <img src="{% static 'img/blog/sidebar_about_thumb.jpg' %}" alt="">
        </div>
        <div class="sidebar-widget-title mb-15">
            <h4>ABOUT THE <span>AUTHOR</span></h4>
        </div>
        <div class="sidebar-about-content">
            <p>Blizzard Game Store</p>
        </div>
    </div>
</div>

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}

        <!-- main-area -->
        <main>

            <!-- breadcrumb-area -->
            <section class="breadcrumb-area breadcrumb-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="breadcrumb-content text-center">
                                <h2>Blog <span>Home</span></h2>
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="{% url 'website:index' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">Blog Home</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- breadcrumb-area-end -->

            <!-- blog-area -->
            <section class="blog-area primary-bg pt-120 pb-175">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8">
                            {% for post in posts %}
                            <div class="blog-list-post">
                                <div class="blog-list-post-thumb">
                                    <a href="blog-details.html"><img src="{{post.image.url}}" alt=""></a>
                                </div>
                                <div class="blog-list-post-content">
                                    <div class="blog-list-post-tag mb-25">
                                        {% for cat in post.category.all %}
                                        <a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>
                                        {% endfor %}
                                    </div>
                                    <h2><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></h2>
                                    <div class="blog-meta">
                                        <ul>
                                            <li>bY <a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author}}</a> / {{post.published_date|date:"d M Y"}} <a>/  Views: {{post.counted_views}}</a></li>
                                        </ul>
                                    </div>
                                    <p>{{post.content}}</p>
                                </div>
                                <div class="blog-list-post-bottom">
                                    <ul>
                                        <li><a href="{% url 'blog:single' pid=post.id %}">more reading<i class="fas fa-angle-double-right"></i></a></li>
                                        <li>
                                            <span>SHARE :</span>
                                            <div class="blog-post-share">
                                                <a href="#"><i class="fab fa-facebook-f"></i></a>
                                                <a href="#"><i class="fab fa-twitter"></i></a>
                                                <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="pagination-wrap mt-60">
                                <ul>
                                    {% if posts.has_previous %}
        
                                    <li><a href="?page={{ posts.previous_page_number }}">Previous</a></li>
                                    {% endif %}
                                    {% for i in posts.paginator.page_range %}
                                    {% if posts.number == i %}
                                    <li><a href="?page={{i}}">{{i}}</a></li>
                                    {% else %}
                                    <li><a href="?page={{i}}">{{i}}</a></li>
                                    {% endif %}
                                    {% endfor %}
                                    {% if posts.has_next %}
                                    <li><a href="?page={{ posts.next_page_number }}">Next</a></li>
                                    {% endif %}
                                </ul>
                            </div>

                        </div>
                        <div class="col-lg-4">
                            <aside class="blog-sidebar">
                                {% include 'blog/blog-author.html' %}
                                {% include 'blog/blog-search.html' %}

                                {% post_categories %}
                                {% latest_posts %}
                            
                            </aside>
                        </div>
                    </div>
                </div>
            </section>
            <!-- blog-area-end -->

        </main>
        <!-- main-area-end -->



{% endblock %}
</html>

templates/blog/blog-post-category.html
{% load static %}
<div class="widget mb-45">
    <div class="sidebar-widget-title mb-25">
        <h4>category <span>post</span></h4>
    </div>
    <div class="sidebar-cat">
        {% for name,count in categories.items %}
        <ul>
            <li><a href="{% url 'blog:category' cat_name=name %}">{{name}} ( {{count}} )</a></li>

        </ul>
        {% endfor %}
    </div>
</div>

templates/blog/blog-search.html
<div class="widget mb-45">
    <div class="sidebar-search">
        <form action="{% url 'blog:search' %}" method="get">
            <input type="text" name="s" placeholder="Search in blogs...">
            <button><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
{% block content %}
<!-- main-area -->
<main>

    <!-- breadcrumb-area -->
    <section class="breadcrumb-area breadcrumb-bg third-breadcrumb-bg">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb-content text-center">
                        <h2>Blog <span>Details</span></h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'website:index' %}">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page"><a
                                        href="{% url 'blog:home' %}">Blog Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">{{post.title}}</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- breadcrumb-area-end -->

    <!-- blog-area -->
    <section class="blog-area primary-bg pt-120 pb-175">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="blog-list-post blog-details-wrap">
                        <div class="blog-list-post-content">
                            <div class="blog-list-post-tag mb-25">
                                {% for cat in post.category.all %}
                                <a href="#">{{cat.name}}</a>
                                {% endfor %}
                            </div>
                            <h2>{{post.title}}</h2>
                            <div class="blog-meta">
                                <ul>
                                    <li>bY <a href="#">{{post.author}}</a> , {{post.published_date|date:"d M Y"}}
                                        <a>, Views: {{post.counted_views}}</a>
                                    </li>
                                </ul>
                            </div>
                            <p>{{post.content}}</p>
                            <div class="row">
                                <!--<div class="col-sm-6">
                                            <div class="blog-details-img">
                                                <img src="{{post.image.url}}" alt="">
                                            </div>
                                        </div>-->
                                <div class="col-sm-10">
                                    <div class="blog-details-img">
                                        <img src="{{post.image.url}}" alt="">
                                    </div>
                                </div>
                            </div>
                            <p>{{post.content}}</p>
                            <blockquote>
                                “ LOREM IPSUM DOLOR AMET CONSECTETUR ADIPISCING ELIT, ukjSED EIUSMOD TEMPOR
                                INCIDIDUNT
                                gaming LABORE ET DOLORE MAGNA ALIQUA”
                            </blockquote>
                            <p>Pellentesque pulvin condium dictum, sapien auctor tortoris vulputate sapien tortor
                                velit. Sed nulla congue euqua
                                molestie grvida ipsum. Curabitr lacus vitae tellus lacinia pretium. Proin vestibulum
                                sollcitudin tortor, quis auctor mi
                                rutru.Nisl nisi scelerisque eu ultrices vitae. Eu lobortis elementum nibh tellus
                                molestie. Tellus orci auctor augue
                                mauris augue neque. Sem fringilla ut morbi tincidunt augue interdum. Sed risus
                                ultricies tristique nulla aliquet enim.</p>
                            <ul class="blog-details-list">
                                <li>Sapien auctor tortoris vulputate sapien ?</li>
                                <li>Curabitr lacus vitae tellus lacinia pretium vulputate ?</li>
                                <li>Tellus orci auctor augue mauris ?</li>
                            </ul>
                            <p>Sapien auctor tortoris vulputate sapien tortor velit. Sed nul congue euqua molestie
                                grvida ipsums Curabitr lacus vitae
                                tellus lacinia pretium. Proin vestibulum sollcitudin tortor, quis auctor rutru.Nisl
                                nisi scelerisque eu ultrices vitae.
                                Eu lobortis elementum nibh tellus molestie.</p>
                            <div class="blog-list-post-bottom">
                                <ul>
                                    <li>
                                        <i class="fas fa-tag"></i>
                                        <span>tags :</span>
                                        {% for tag in post.tags.all %}
                                        <a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>
                                        {% endfor %}

                                    </li>
                                    <li>
                                        <span>SHARE :</span>
                                        <div class="blog-post-share">
                                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                                            <a href="#"><i class="fab fa-twitter"></i></a>
                                            <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>



                    <div class="row">
                        {% if previous_post.id %}
                        <div class="col-lg-6">
                            <div class="latest-match-box-two mb-30">
                                <div class="latest-match-thumb-two">
                                    <img src="{{previous_post.image.url}}">
                                </div>
                                <div class="tournament-schedule-content">
                                    <h3><a
                                            href="{% url 'blog:single' pid=previous_post.id %}"><span>{{previous_post.title}}</span></a>
                                    </h3>
                                    <div class="tournament-schedule-meta">
                                        <a href="{% url 'blog:single' pid=previous_post.id %}">Previous Post</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if next_post.id %}
                        <div class="col-lg-6">
                            <div class="latest-match-box-two mb-30">
                                <div class="latest-match-thumb-two">
                                    <img src="{{next_post.image.url}}">
                                </div>
                                <div class="tournament-schedule-content">
                                    <h3><a href="{% url 'blog:single' pid=next_post.id %}"><span
                                                style="font-size: 16px">{{next_post.title}}</span></a></h3>
                                    <div class="tournament-schedule-meta">
                                        <a href="{% url 'blog:single' pid=next_post.id %}">Next Post</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>

                    <div class="blog-comment mb-75">
                        <div class="sidebar-widget-title blog-details-title mb-35">
                            {% if comments %}
                            <h4>COMMENTS: <span>{{comments|length}}</span></h4>
                            {% else %}
                            <h4>No <span>Comments</span></h4>
                            {% endif %}
                        </div>
                        {% for comment in comments %}
                        <ul>
                            <li>
                                <div class="comment-avatar-thumb">
                                    <img src="{% static 'img/blog/comment_thumb01.jpg' %}" alt=""
                                        style="width:80px;height:80px;">
                                </div>
                                <div class="comment-text">
                                    <div class="comment-avatar-info">
                                        <h4><a href="#">{{comment.name}}</a><span
                                                class="comment-time">{{comment.created_date|naturalday}}</span></h4>
                                    </div>
                                    <p>{{comment.message}}</p>
                                </div>
                            </li>
                            {% empty %}
                            <p>No comments yet. Be the first one to comment!</p>
                        </ul>
                        {% endfor %}
                    </div>

                    <div class="comment-reply-box">
                        <div class="sidebar-widget-title blog-details-title mb-35">
                            <h4>LEAVE A <span>COMMENT</span></h4>
                        </div>
                        <form method="post" action="{% url 'blog:single' pid=post.id %}" class="comment-form">
                            {% csrf_token %}
                            <input type="hidden" name="post" value="{{post.id}}">
                            {% if request.user.is_authenticated %}
                            <input type="hidden" name="name" value="{{request.user.first_name}}">
                            <input type="hidden" name="email" value="{{request.user.email}}">
                            {% else %}
                            <div class="row">
                                <div class="col-md-6">
                                    <input name='name' type="text" placeholder="Your Name*">
                                </div>
                                <div class="col-md-6">
                                    <input name="email" type="email" placeholder="Your Email*">
                                </div>
                            </div>
                            {% endif %}
                            <textarea name="message" placeholder="Your Comment"></textarea>
                            <div class="comment-check-box mb-25">
                                <input type="checkbox" id="comment-check">
                                <label for="comment-check">Save my name and email in this browser for the
                                    next time I comment.</label>
                            </div>
                            <button type="submit" class="btn btn-style-two">Submit</button>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <aside class="blog-sidebar">

                        {% include 'blog/blog-author.html' %}

                        {% include 'blog/blog-search.html' %}
                        {% post_categories %}
                        {% latest_posts %}
                        {% include 'blog/blog-tags.html' %}

                    </aside>
                </div>
            </div>
        </div>
    </section>
    <!-- blog-area-end -->

</main>
<!-- main-area-end -->

<!-- Mirrored from themebeyond.com/html/geco/Geco/blog-details.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 02 Sep 2022 19:11:33 GMT -->
{% endblock %}

templates/blog/blog-tags.html
<div class="widget">
    <div class="sidebar-widget-title mb-25">
        <h4>TAGS <span>post</span></h4>
    </div>
    <div class="sidebar-tag-list">
        <ul>
            {% for tag in post.tags.all %}
            <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/blog/latest-posts.html
{% load humanize %}
<div class="widget mb-45">
    <div class="sidebar-widget-title mb-25">
        <h4>Recent <span>post</span></h4>
    </div>
    
    <div class="rc-post-list">
        <ul>
            {% for post in posts %}
            <li>
                
                <div class="rc-post-thumb">
                    <a href="{% url 'blog:single' pid=post.id %}"><img src="{{post.image.url}}" alt=""></a>
                </div>
                <div class="rc-post-content">
                    <h5><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></h5>
                    <span>{{post.published_date|naturaltime}}</span>
                </div>
                
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/blog/most-viewed-posts.html
<div class="col-xl-6 col-lg-8">
    <div class="blog-area mb-120">
        <div class="tournament-top-wrap">
            <div class="section-title tournament-title">
                <h2>Most Viewed <span>Articles</span></h2>
            </div>
        </div>
        <div class="blog-post-wrap">
            {% for post in posts %}
            <div class="blog-post-item blog-style-one">
                <div class="blog-thumb">
                    <a href="{% url 'blog:single' pid=post.id %}"><img src="{{post.image.url}}" alt=""></a>
                </div>
                <div class="blog-post-content">
                    <h5><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></h5>
                    <div class="blog-meta">
                        <ul>
                            <li><i class="far fa-clock"></i>{{post.published_date|date:"d M Y"}}</li>
                            <li><i class="fas fa-heart"></i>{{post.counted_views}}</li>
                        </ul>
                    </div>
                    <p>{{post.content|truncatewords:10}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    salam

    {{posts}}

</body>
</html>